// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type UploadedFile struct {
	TransactionUuid      uuid.UUID
	Consumer             string
	UserName             string
	FileName             string
	FileSize             sql.NullInt32
	FileType             sql.NullString
	UploadPresignedUrl   string
	DownloadPresignedUrl sql.NullString
	Status               string
	CreatedAt            time.Time
	UpdatedAt            sql.NullTime
}
